pipeline:

  build:
    image: spritsail/docker-build
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
    repo: iodine-dev

  tag:
    image: docker
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
    commands:
      - docker inspect -f '{{ index .Config.Labels "io.spritsail.version.iodine" }}' iodine-dev > .iodine_ver

  publish:
    image: spritsail/docker-publish
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
    secrets: [ docker_username, docker_password, microbadger_token ]
    when: { event: [push, tag, deployment] }
    from: iodine-dev
    repo: spritsail/iodine
    tags:
      - 'latest'
      - '%file: .iodine_ver'

  notify:
    image: spritsail/notify
    when: { status: [ success, failure ] }
    secrets: [ webhook_url, notify_token ]
