pipeline:
  identify:
    image: docker
    commands:
      - set -o pipefail
      - apk add --no-cache curl git jq
      - git clone git://git.netfilter.org/iptables /tmp/iptables
      - echo $(git -C /tmp/iptables describe --tags $(git -C /tmp/iptables rev-list --tags --max-count=1) | sed -e 's/^v//') > .iptables_ver
      - echo $(curl -fLqsS 'https://api.github.com/repos/madler/zlib/tags' | jq -r '.[0].name' | sed -e 's/^v//') > .zlib_ver
      - echo $(curl -fLqsS http://code.kryo.se/iodine/ | sed -n 's/Latest.*:.*<b>\([0-9\.]*\).*/\1/p') > .iodine_ver

  build:
    image: spritsail/docker-build
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
    repo: iodine-dev
    build_args:
      - 'IPTABLES_VER=%file: .iptables_ver'
      - 'ZLIB_VER=%file: .zlib_ver'
      - 'IODINE_VER=%file: .iodine_ver'

  test:
    image: docker
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
    commands:
      - CON_NAME=$(docker run -d -p 53:53/udp --cap-add=NET_ADMIN --device /dev/net/tun -e IODINE_HOST=tunnel.example.com -e IODINE_PASS=password iodine-dev)
      - timeout -t 5 docker logs $$CON_NAME &
      - sleep 2
      - IP=$(docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $$CON_NAME)
      - if [ -z "$IP" ]; then
            echo "The container exited.. sadpanda";
            docker inspect --format='{{.State.ExitCode}}' $$CON_NAME;
            docker rm $$CON_NAME
            exit 25;
        fi
      - docker kill $$CON_NAME
      - docker rm $$CON_NAME

  publish:
    image: spritsail/docker-publish
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
    secrets: [ docker_username, docker_password, microbadger_token ]
    when: { event: [push, tag, deployment] }
    from: iodine-dev
    repo: spritsail/iodine
    tags:
      - 'latest'
      - '%file: .iodine_ver'

  notify:
    image: appleboy/drone-telegram
    when: { status: [ success, failure ] }
    secrets: [ telegram_token, telegram_to ]
    message: |
      *{{repo.owner}}/{{repo.name}} [{{commit.branch}}]*: Build #{{build.number}}: *{{uppercase build.status}}*
      {{build.link}}
