pipeline:
  build:
    image: spritsail/docker-build
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
    repo: iodine-frekky-dev

  publish:
    image: spritsail/docker-publish
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
    secrets: [ docker_username, docker_password, microbadger_token ]
    when: { branch: [ frekky ], event: [ push, tag, deployment ] }
    from: iodine-frekky-dev
    repo: spritsail/iodine
    tags:
      - '%label io.spritsail.version.iodine | %prefix frekky | %auto'
  notify:
    image: spritsail/notify
    when: { status: [ success, failure ] }
    secrets: [ webhook_url, notify_token ]
